from __future__ import annotations

from typing import Protocol


class BrokerProvider(Protocol):
    name: str

    def get_account(self) -> dict: ...

    def get_positions(self) -> list[dict]: ...

    def get_orders(self, status: str = "all", symbol: str = "", asset_class: str = "", after: str = "", until: str = "") -> list[dict]: ...

    def get_order(self, order_id: str) -> dict: ...

    def get_order_by_client_id(self, client_order_id: str) -> dict | None: ...

    def get_fills(self) -> list[dict]: ...

    def get_activities(self, activity_types: str = "", after: str = "", until: str = "") -> list[dict]: ...

    def get_market_clock(self) -> dict: ...

    def get_asset(self, symbol: str) -> dict: ...

    def submit_entry_order(self, body: dict) -> dict: ...

    def submit_exit_order(self, body: dict) -> dict: ...

    def cancel_order(self, order_id: str) -> None: ...

    def replace_order(self, order_id: str, body: dict) -> dict: ...

    def sync_positions(self) -> list[dict]: ...

    def reconcile(self) -> dict: ...
