create table public.position_states (
  trade_id text primary key,
  symbol text not null,
  underlying text not null,
  status text not null default 'open',
  entry_fill_price numeric not null,
  entry_fill_quantity integer not null,
  entry_time timestamptz not null,
  entry_underlying_price numeric,
  entry_delta numeric,
  entry_iv numeric,
  entry_option_price numeric not null,
  peak_option_price numeric not null,
  peak_time timestamptz not null,
  planned_risk numeric not null,
  one_r_amount numeric not null,
  initial_stop_price numeric not null,
  protected_stop_price numeric not null,
  target_1 numeric not null,
  target_2 numeric not null,
  trailing_active boolean not null default false,
  trailing_peak numeric not null,
  trailing_trigger numeric not null,
  expiration text not null default '',
  dte_at_entry integer not null default 0,
  underlying_direction text not null default '',
  thesis text not null default '',
  invalidation text not null default '',
  risk_policy_version text not null default '',
  exit_policy_version text not null default '',
  protected_mode boolean not null default false,
  winner_run_mode boolean not null default false,
  current_option_bid numeric,
  current_option_ask numeric,
  current_underlying_price numeric,
  current_iv numeric,
  current_spread numeric,
  current_unrealized_pnl numeric,
  current_holding_minutes numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.position_states enable row level security;
